version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: otp-postgres
    environment:
      POSTGRES_DB: otp_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  mailhog:
    image: mailhog/mailhog:latest
    container_name: otp-mailhog
    ports:
      - "1025:1025" # SMTP сервер
      - "8025:8025" # Web интерфейс
    restart: unless-stopped

volumes:
  postgres_data: 